--TEST--
Testing throw exception doesn't crash with wrong params, variant 4
--FILE--
<?crx

throw new Error(new stdClass);

?>
--EXPECTF--
Fatal error: Uncaught TypeError: Error::__main(): Argument #1 ($message) must be of type string, stdClass given in %s:%d
Stack trace:
#0 %sexception_022.crx(%d): Error->__main(Object(stdClass))
#1 {main}
  thrown in %sexception_022.crx on line %d
